template_path: remote/peer-route-config.yaml
stack_name: peer-vpc-admincentral
parameters:
  PeeringConnectionId: pcx-4904f521
  VpcPrivateRouteTable: rtb-3d932341
  VpcPublicRouteTable: rtb-c49d2db8
  VpnCidr: 10.1.0.0/16
hooks:
  before_update:
    - !cmd "curl https://s3.amazonaws.com/{{stack_group_config.admincentral_cf_bucket}}/aws-infra/master/peer-route-config.yaml --create-dirs -o templates/remote/peer-route-config.yaml"
